# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

jobs:
- job: ExportToGitHub
  displayName: Export to GitHub
  steps:
    - checkout: none

    # Mirror clone the Azure DevOps repository
    - script: |
        git clone --mirror https://$(System.AccessToken)@dev.azure.com/OneHRADO/Microsoft_Leap/_git/Push_Code_From_ADO_To_GitHub_Pipeline repo-mirror
        cd repo-mirror
      env:
        System.AccessToken: $(System.AccessToken)
      displayName: "Mirror clone from Azure DevOps"

    # Set up Git to authenticate with GitHub
    - script: |
        cd repo-mirror
        git remote set-url --push origin https://AruseyDaisy:$(GITHUB_TOKEN)@github.com/Leap-Internal-Program/Push_Code_From_ADO_GitHub_Pipeline-.git
        git push --mirror
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: "Push mirror to GitHub"
